server {
    listen 8000;
    client_body_timeout 600s;
    client_max_body_size 500M;
    root /var/www/agilityasturias/agility_back/public;
    index index.php;

    location /storage/ {
        alias /var/www/agilityasturias/agility_back/storage/app/public/;
        access_log off;
        expires max;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.4-fpm.sock;
    }
}

server {
    client_body_timeout 600s;
    proxy_read_timeout 600s;
    proxy_connect_timeout 600s;
    proxy_send_timeout 600s;
    client_max_body_size 500M;
    server_name agilityasturias.com www.agilityasturias.com clubagility.com www.clubagility.com agilityasturias.clubagility.com www.agilityasturias.clubagility.com patitas.clubagility.com www.patitas.clubagility.com xanastur.clubagility.com www.xanastur.clubagility.com leonidogs.clubagility.com www.leonidogs.clubagility.com elnorte.clubagility.com www.elnorte.clubagility.com;

    root /var/www/agilityasturias/frontend/dist/ClubAgility/browser;
    index index.html index.htm;

    location /storage/ {
        alias /var/www/agilityasturias/agility_back/storage/app/public/;
        access_log off;
        expires max;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /backend/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/agilityasturias.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/agilityasturias.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot












}

server {
    if ($host = www.leonidogs.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = leonidogs.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = www.xanastur.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = xanastur.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = www.patitas.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = patitas.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = www.agilityasturias.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = agilityasturias.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = www.clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = clubagility.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = www.agilityasturias.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = agilityasturias.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80 default_server;
    server_name agilityasturias.com www.agilityasturias.com clubagility.com www.clubagility.com agilityasturias.clubagility.com www.agilityasturias.clubagility.com patitas.clubagility.com www.patitas.clubagility.com xanastur.clubagility.com www.xanastur.clubagility.com leonidogs.clubagility.com www.leonidogs.clubagility.com elnorte.clubagility.com www.elnorte.clubagility.com;
    return 404; # managed by Certbot




}
